proxy-groups:
  - name: 全球直连
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Direct.png
    type: select
    proxies:
      - DIRECT

  - name: Proxies
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Proxy.png
    type: select
    proxies:
      - 自动选择
      - 省流节点
      - 新加坡
      - 香港
      - 美国
      - 手动切换

  - name: 手动切换
    icon: https://cdn.jsdelivr.net/gh/shindgewongxj/WHATSINStash@master/icon/select.png
    include-all: true
    type: select

  - name: 自动选择
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Auto.png
    type: url-test
    include-all: true
    exclude-filter: "(?i)家宽|家庭|商宽|落地|IEPL|游戏|海外"
    interval: 300
    tolerance: 20
    lazy: false

  - name: 省流节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Auto.png
    type: url-test
    include-all: true
    exclude-filter: "(?i)IEPL"
    interval: 300
    tolerance: 20
    lazy: false

  - name: 新加坡
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png
    type: url-test
    include-all: false
    include-filter: "(?i)新加坡|Singapore|SG"
    interval: 300
    tolerance: 20
    lazy: false

  - name: 香港
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png
    type: url-test
    include-all: false
    include-filter: "(?i)香港|HongKong|HK"
    interval: 300
    tolerance: 20
    lazy: false

  - name: 美国
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png
    type: url-test
    include-all: false
    include-filter: "(?i)美国|UnitedStates|US|USA"
    interval: 300
    tolerance: 20
    lazy: false

  - name: 人工智能
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bot.png
    type: select
    proxies:
      - Proxies
      - 新加坡
      - 香港
      - 美国
      - 手动切换
      - 全球直连

  - name: 加密货币
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Cryptocurrency_3.png
    type: select
    proxies:
      - Proxies
      - 新加坡
      - 香港
      - 美国
      - 手动切换
      - 全球直连

  - name: Telegram
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png
    type: select
    proxies:
      - Proxies
      - 新加坡
      - 香港
      - 美国
      - 手动切换
      - 全球直连

  - name: Google
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png
    type: select
    proxies:
      - Proxies
      - 新加坡
      - 香港
      - 美国
      - 手动切换
      - 全球直连

  - name: YouTube
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
    type: select
    proxies:
      - Proxies
      - 新加坡
      - 香港
      - 美国
      - 手动切换
      - 全球直连

  - name: Netflix
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Netflix.png
    type: select
    proxies:
      - Proxies
      - 新加坡
      - 香港
      - 美国
      - 手动切换
      - 全球直连


  - name: 学术资源
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Scholar.png
    type: select
    proxies:
      - Proxies
      - 新加坡
      - 香港
      - 美国
      - 手动切换
      - 全球直连

  - name: 游戏平台
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Game.png
    type: select
    proxies:
      - Proxies
      - 新加坡
      - 香港
      - 美国
      - 手动切换
      - 全球直连

  - name: 微软服务
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Microsoft.png
    type: select
    proxies:
      - Proxies
      - 新加坡
      - 香港
      - 美国
      - 手动切换
      - 全球直连

  - name: AppleAI
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Apple.png
    type: select
    proxies:
      - Proxies
      - 新加坡
      - 香港
      - 美国
      - 手动切换
      - 全球直连

  - name: 静态资源
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Cloudflare.png
    type: select
    include-all: true
    proxies:
      - Proxies
      - 自动选择
      - 手动切换
      - 省流节点
      - 新加坡
      - 香港
      - 美国
      - 全球直连

  - name: FCM推送
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png
    type: select
    proxies:
      - 全球直连
      - Proxies
      - 新加坡
      - 香港
      - 美国

  - name: Steam修复
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Steam.png
    type: select
    proxies:
      - 全球直连
      - Proxies
      - 新加坡
      - 香港
      - 美国

  - name: 漏网之鱼
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Final.png
    type: select
    proxies:
      - Proxies
      - 全球直连
      - 手动切换
      - 省流节点
      - 新加坡
      - 香港
      - 美国


rule-providers:
  Microsoft:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/microsoft.txt
    path: ./sukkaw_ruleset/microsoft_non_ip.txt

  game-download:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/domainset/game-download.txt
    path: ./sukkaw_ruleset/game-download.txt

  cdn_domainset:
    type: http
    behavior: domain
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/domainset/cdn.txt
    path: ./sukkaw_ruleset/cdn_domainset.txt

  cdn_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/cdn.txt
    path: ./sukkaw_ruleset/cdn_non_ip.txt

  apple_cdn:
    type: http
    behavior: domain
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/domainset/apple_cdn.txt
    path: ./sukkaw_ruleset/apple_cdn.txt

  microsoft_cdn_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/microsoft_cdn.txt
    path: ./sukkaw_ruleset/microsoft_cdn_non_ip.txt

  ai_non_ip:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/ai.txt
    path: ./sukkaw_ruleset/ai_non_ip.txt

  SteamFix:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/SteamFix.list
    path: ./ruleset/SteamFix.list

  GoogleFCM:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/FirebaseCloudMessaging.list
    path: "./ruleset/FirebaseCloudMessaging.list"

  AdditionalFilter:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/AdditionalFilter.list
    path: ./ruleset/AdditionalFilter.list

rules:
  - "RULE-SET,game-download,DIRECT"
  - "RULE-SET,cdn_domainset,静态资源"
  - "RULE-SET,cdn_non_ip,静态资源"
  - "RULE-SET,apple_cdn,全球直连"
  - "RULE-SET,microsoft_cdn_non_ip,全球直连"
  - "RULE-SET,ai_non_ip,人工智能"
  - "RULE-SET,Microsoft,微软服务"
  - "RULE-SET,SteamFix,Steam修复"
  - "RULE-SET,GoogleFCM,FCM推送"
  - "GEOSITE,GOOGLEFCM,FCM推送"
  - "GEOSITE,GOOGLE-PLAY@CN,全球直连"
  - "GEOSITE,GOOGLE,Google"
  - "GEOSITE,YOUTUBE@CN,全球直连"
  - "GEOSITE,YOUTUBE,YouTube"
  - "GEOSITE,NETFLIX,Netflix"
  - "GEOSITE,CATEGORY-GAMES@CN,全球直连"
  - "GEOSITE,CATEGORY-GAMES,游戏平台"
  - "GEOSITE,CATEGORY-SCHOLAR-!CN,学术资源"
  - "GEOSITE,CATEGORY-SCHOLAR-CN,全球直连"
  - "GEOSITE,CATEGORY-CRYPTOCURRENCY,加密货币"
  - "GEOSITE,TELEGRAM,Telegram"
  - "GEOSITE,GEOLOCATION-!CN,Proxies"
  - "GEOSITE,CN,全球直连"
  - "GEOSITE,PRIVATE,全球直连"
  - "GEOIP,NETFLIX,Netflix,no-resolve"
  - "GEOIP,GOOGLE,Google,no-resolve"
  - "GEOIP,TELEGRAM,Telegram,no-resolve"
  - "GEOIP,CN,全球直连,no-resolve"
  - "GEOIP,LAN,全球直连,no-resolve"
  - "GEOIP,PRIVATE,全球直连,no-resolve"
  - "DOMAIN-KEYWORD,xrh0905.top,DIRECT"
  - "DOMAIN-KEYWORD,xhome.top,DIRECT"
  - "DOMAIN-KEYWORD,xrhhk.top,DIRECT"
  - "DOMAIN-KEYWORD,xiaowuap.com,DIRECT"
  - "DOMAIN-KEYWORD,todayeat.fun,DIRECT"
  - "IP-CIDR,192.168.0.0/16,DIRECT"
  - "DOMAIN-KEYWORD,stun,DIRECT"
  - "DOMAIN-KEYWORD,turn,DIRECT"
  - "DOMAIN-KEYWORD,adobe.io,REJECT"
  - "DOMAIN-KEYWORD,adobestats.io,REJECT"
  - "DOMAIN,time.windows.com,DIRECT"
  - "DOMAIN-KEYWORD,ntp,DIRECT"
  - "DOMAIN-KEYWORD,epdg.epc.mnc011.mcc460.pub.3gppnetwork.org,DIRECT"
  - "DOMAIN-KEYWORD,fr24.com,Proxies"
  - "DOMAIN-KEYWORD,flightradar24.com,Proxies"
  - "DOMAIN-KEYWORD,sp288.top,DIRECT"
  - "DOMAIN-KEYWORD,duolingo,Proxies"
  - "DOMAIN-KEYWORD,aliyuncs.com,DIRECT"
  - "IP-CIDR,59.59.0.0/16,DIRECT"
  - "DOMAIN-KEYWORD,gspe1-ssl.ls.apple.com,AppleAI"
  - "DOMAIN,apple-relay.apple.com,AppleAI"
  - "DOMAIN,apple-relay.cloudflare.com,AppleAI"
  - "DOMAIN,apple-relay.fastly-edge.com,AppleAI"
  - "DOMAIN,apple-relay.mask.apple-dns.net,AppleAI"
  - "DOMAIN-KEYWORD,epdg.epc.mnc015.mcc234.pub.3gppnetwork.org,Proxies"
  - "DOMAIN-KEYWORD,ss.epdg.epc.mnc015.mcc234.pub.3gppnetwork.org,Proxies"
  - "DOMAIN-KEYWORD,ss.epdg.epc.geo.mnc015.mcc234.pub.3gppnetwork.org,Proxies"
  - "DOMAIN-KEYWORD,entsrv-uk.vodafone.com,Proxies"
  - "DOMAIN-KEYWORD,vuk-gto.prod.ondemandconnectivity.com,Proxies"
  - "DOMAIN-KEYWORD,fei288.cn,DIRECT"
  - "DOMAIN-KEYWORD,ui.com,DIRECT"
  - "IP-CIDR,88.82.0.0/19,Proxies"
  - "IP-CIDR,46.68.0.0/17,Proxies"
  - "IP-CIDR,87.194.0.0/16,Proxies"
  - "SRC-IP-CIDR,10.44.77.0/24,DIRECT"
  - "DOMAIN-KEYWORD,ocsp,DIRECT"
  - "DST-PORT,9993,DIRECT"
  - "MATCH,漏网之鱼"


sniffer:
  sniff:
    HTTP:
      ports: [80, 8080, 8880]
      override-destination: false
    TLS:
      ports: [443, 8443]
      override-destination: true
    QUIC:
      ports: [443, 8443]
      override-destination: true
  enable: true
  parse-pure-ip: true
  force-dns-mapping: true
  skip-domain:
    - "Mijia Cloud"
    - "dlg.io.mi.com"
    - "+.push.apple.com"

dns:
  enable: true
  ipv6: true
  prefer-h3: true
  enhanced-mode: redir-host
  use-system-hosts: true
  default-nameserver:
    - "119.28.28.28"
    - "119.29.29.29"
    - "223.5.5.5"
    - "223.6.6.6"
  nameserver:
    - "system"
    - "quic://223.5.5.5"
    - "tls://dot.pub:853"
    - "tls://dns.alidns.com:853"
    - "https://doh.pub/dns-query"
    - "https://dns.alidns.com/dns-query"
  fallback:
    - "https://dns.cloudflare.com/dns-query"
    - "https://dns.sb/dns-query"
    - "https://dns.google/dns-query"
    - "https://public.dns.iij.jp/dns-query"
    - "https://jp.tiar.app/dns-query"
    - "https://jp.tiarap.org/dns-query"
  proxy-server-nameserver:
    - "quic://223.5.5.5"
    - "tls://dot.pub:853"
    - "https://223.5.5.5/dns-query"

geodata-mode: true

geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb"
  asn: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/GeoLite2-ASN.mmdb"